services:
  mysql:
    image: mysql:8.0
    container_name: mysqldb
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: url_shortener
      MYSQL_USER: admin
      MYSQL_PASSWORD: dev4wm
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - hyve

  backend:
    image: node:18-alpine
    container_name: backend
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    command: sh -c "npm install && npm run start:dev"
    ports:
      - '3333:3333'
    depends_on:
      - mysql
    networks:
      - hyve

networks:
  hyve:

volumes:
  mysql_data:
